language: node_js
node_js:
- 0.10
before_script:
  - "npm install -g se-interpreter"
script:
  - "se-interpreter interpreter_config.json"

env:
  global:
    - SAUCE_USERNAME=jackchem2003
    - SAUCE_ACCESS_KEY=3d4fa22d-12ad-4f18-9168-37ea7d88b522
