language: node_js
before_script:
  - "npm isntall -g se-interpreter"
script:
  - "se-interpreter interpreter_config.json"
env:
  global:
    - SAUCE_USERNAME=jackchem2003
    - secure: "3d4fa22d-12ad-4f18-9168-37ea7d88b522"
