sudo: false
language: node_js
node_js:
- 0.10
before_script:
  - "npm install -g se-interpreter"
script:
  - "se-interpreter interpreter_config.json"

env:
  global:
    - secure: dTl/lRxzv/0vpQ7XfOZ2EczZ3x329pUsu1MZYnNpWsR0UbxXhv5P8ee1J+lw8jCUNN2JeHkgYYbMDcg8gXUtxeme3WT/PXCcnusqVHcc7pwN3Tv0nuUNZdSPdZSmD4DlEZ8qpgZQQJajp4M/J+63UgfRELGhagYzE6bTVppJNvhDo3BhHKi4CYkc4CerrY2gfNwYdpNIsoaF+WXAZy9Kz/FxEruZAFR34k8LMjR8AO9/Ytuxt60wvgE7LY8s9XIs6YBcgc6pevj9mhn9/q+ns9zbT7VNTybR8AMqik6Ob1/P8DrK/Ldj6K7zL7W78cVoTsVakwRS+ESkbEjX0bMQaz05LMTnJV+/7D+Tiivz1hk0vNVqOd9m0maN9PZOcEToonJYA4Di0I6XvLmejlRYWKTdQpuz+rKuG+Xw8H3pkeJC3XOXiZfTIcg0fML07myLE3Jw5/E0a0wp3OooelN4Yinor80u66QAWt6h3DozrPLrH2qPG9avVdah2blZcsnIs9YmZqwduhqecND9zncukak/eU/i0qDkIh30J8cTiYA2h/jlQZulkLobk92eJYdlislF9ymB44ppooBk24SDkT8yhgbj0Re5RAqqpIJYGMBs7+d44o2dIq06l+VkeAI7a6c/7/cSn+GEsssAMI0EPO4w2/ye5RsyvNN8YKP22Wk=
    - secure: hOF63Fk9Ad1TNZ8dlHtGgmi2DQ6T3HvLEGEiaoEJ8pAvLGpxD5lkBhWb9ZU+DkTF5VeHmf/TeiSrZmgF2HH3fEKPKm1s4Xev2+vLSE9ADfgRLfyTLDHm1dkLdhjwFRTp67epEOibsfR03DWvKaLH4GqHdAgSqyCHUaBegZqxZAgI7Zpd4XkrNRYrMiAOyPh/AGHgnqRrdzmn5ujOXPJE5QujFenVxUyvad+UKYsKoQNCYwxsNlqTrrHq5qNIWAUuvuQ7po6598y+4M6fVNStjEohs3YTE10MRNnNI35hyySMu967DVgNp4NrYX0aqosBn3cRXx1rjqsX6kS7Gd5zy/Qot7it+u5WUECDeD7ZkBOIzRpet/LjI/TJ5N4JvMICqfErE63CIz210Ed75O5aP0J5T/bourg5WZlqQ7W20pgK/7665XjnMXc1BZ/yaurFpKKIgixTX9b5Xc3p4dQi3NxmdcGZ7NyF2ZYl/Lg882FpfbtRdn5i2MzmI7ULMDcYAxFTUINqQT+U4wB8HgWTWXNPeRvWff256smopz3YmX7oJ3F6hxNDb6skfziDyeMFxleRqY/qj3sxHLZSjrXXZ4r0zkwpi948DLKgBShzOrDMZpPkzV2sR0Ou9BM8EIcrflsgRy15lKtbuDXxAIZYKBsFaCcN0yQx91c4ccGBaJE=
addons:
  sauce_connect: true
